baseURL = "https://pepotech.netlify.app/"
languageCode = "en-us"
title = "PepoTech"
theme = "PaperMod"
defaultContentLanguage = "en"
enableRobotsTXT = true

[pagination]
  pagerSize = 25

[params]
  author = "Giuseppe"
  description = "Glossario tech semplice per sviluppatori alle prime armi"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  disableSpecial1stPost = true
  customHead = '''
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4654113948534658"
     crossorigin="anonymous"></script>
  '''


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Glossario"
  url = "/posts/"
  weight = 2
